# Use Python 3.12 as the base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the requirements file to docker image
COPY requirements.txt ./

RUN apt-get update \
&& apt-get install -y ffmpeg libsm6 libxext6 \
&& pip3 install -r requirements.txt --no-cache-dir

# Copy the application code to the image
COPY app/ ./